# Generated by Django 5.0.7 on 2024-07-18 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Blogs Category',
        ),
    ]
