# Generated by Django 5.0.7 on 2024-07-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='blogs_category',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='blog_tags',
        ),
    ]
