# Generated by Django 5.0.7 on 2024-07-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_alter_category_table_alter_tag_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
