# Generated by Django 5.0.7 on 2024-08-02 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0004_remove_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('can_comment', 'Can comment on blogs')]},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_write_blogs', 'Can write blogs')]},
        ),
    ]
