# Generated by Django 5.0.7 on 2024-08-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
